### ISSUE TITLE
Bad request error for getFloat function reading from setup Firebase Realtime Database

### ISSUE THREAD

**Issue by tyounkin** [mobizt/Firebase-Arduino-WiFiNINA#10]
Hi, I am using the Arduino Uno wifi rev2 to try to read (and eventually write) to firebase RTDB. I am getting a 'bad request' error. Is there a method of debugging my request? Please let me know if I can provide more details to help. Thanks!

**Comment by mobizt** [comment]
You are missing the required data or its data is empty e.g. FIREBASE_HOST, FIREBASE_AUTH and path in the functions that you want to store or read the value. 

Please read the usage examples [here](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/tree/master/examples).
