### ISSUE TITLE
A suggestion how to have one library for all WiFi libraries

### ISSUE THREAD

**Issue by jandrassy** [mobizt/Firebase-Arduino-WiFiNINA#11]
with this you can have one library for WiFiNINA, WiFi101 and my WiFiEspAT library.
```
#if __has_include(<WiFi101.h>)
#include <WiFi101.h>
#else
#include <WiFi.h>
#endif
```
what library will be used is determined by the include in sketch. then WiFiNINA and my library have WiFi.h. For WiFi101 my [PR](https://github.com/arduino-libraries/WiFi101/pull/291) to add WiFi.h was not accepted yet so the trick with  `__has_include` is necessary.

I didn't look close at the esp8266 and esp32 versions of your library, but ESP32 has WiFi.h and for esp8266 this should work:
```
#if __has_include(<WiFi101.h>)
#include <WiFi101.h>
#elif defined(ESP8266)
#include <ESP8266WiFi.h>
#else
#include <WiFi.h>
#endif
```
EDIT: it is not necessary to include SPI.h. the libraries which use it will include it.

related: https://github.com/jandrassy/WiFiEspAT/issues/21

**Comment by mobizt** [comment]
I intend to make the WiFiClient and SSL/TLS dependent.

All platforms have different WiFi library class and SSL/TLS compiled library included their specific functions that are not derived from WiFiClient base class.
