### ISSUE TITLE
readStream error

### ISSUE THREAD

**Issue by ik2wxx** [mobizt/Firebase-Arduino-WiFiNINA#13]
Hi
After some minutes of use, Firebase.readStream(firebaseData) returns false, also if data is still readable and firebaseData.streamTimeout() returns false.
I'm now ignoring that message
```
if (!Firebase.readStream(firebaseData)) {
    Serial.print("Can't read stream data");
}
```

**Comment by mobizt** [comment]
It is due to unstable internet connection. The stream connection is timed out as the heartbeat data is missing over the 30 seconds.
