### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ThomasKientz** [mobizt/Firebase-Arduino-WiFiNINA#17]
I have the following error :

```
----------Can't set data--------
REASON: connection refused
--------------------------------
```
I have tried with both `databaseURL` and `authDomain` from the config.

```
const firebaseConfig = {
  apiKey: "secret",
  authDomain: "myproject.firebaseapp.com",
  databaseURL: "https://myproject-default-rtdb.europe-west1.firebasedatabase.app",
  projectId: "myproject",
  storageBucket: "myproject.appspot.com",
  messagingSenderId: "secret",
  appId: "secret"
};
```

I have used the database secret :

<img width="1018" alt="Capture d’écran 2021-04-08 à 09 50 58" src="https://user-images.githubusercontent.com/10157845/113989277-933d3600-9850-11eb-8325-a41260262583.png">

**Comment by ThomasKientz** [comment]
Firmware is updated. Do I need to add a SSL certificate as well ?

**Comment by mobizt** [comment]
The FIREBAE_HOST value is only host name without https:// scheme and back slash.

In your case it might be **myproject-default-rtdb.europe-west1.firebasedatabase.app**

Please make sure by go to your Firebase RTDB console and you will find the url above your database tree.

For example, if the database url is https://xxxxxxxxxxx.firebaseio.com/ then the FIREBASE_HOST will be **xxxxxxxxxxx.firebaseio.com**

FIREBASE_AUTH is your database secret as in your post image.

No server SSL cert required if you already update the Firmware.

**Comment by mobizt** [comment]
You may try to renew the database secret and use the new database secret.

**Comment by ThomasKientz** [comment]
Thanks it works !

I have remove https:// and back slash so in my case i end up with `myproject-default-rtdb.europe-west1.firebasedatabase.app`.

And I have also renew the db secret.
