### ISSUE TITLE
Unable to specify pushId

### ISSUE THREAD

**Issue by Cole-Brooks** [mobizt/Firebase-Arduino-WiFiNINA#25]
It seems as though you're limited to using the random push Id assigned by firebase. This is a feature request to add that as a push parameter.

**Comment by mobizt** [comment]
Are you new to Firebase RTDB?

Please read [this document](https://firebase.google.com/docs/database/rest/save-data#section-put).
This is [how Firebase creates the UID](https://firebase.googleblog.com/2015/02/the-2120-ways-to-ensure-unique_68.html).

**Comment by Cole-Brooks** [comment]
Thanks for the info!
