### ISSUE TITLE
How to read Firebase timestamps

### ISSUE THREAD

**Issue by matzesoft** [mobizt/Firebase-Arduino-WiFiNINA#27]
Hi. I am currently trying to read timestamps stored in Firebase on my Arduino Nano 33 IoT.
However timestamps are very high numbers. The current timestamp I am writing this message for example is: 1634573019348.

Using the `getInt()` function doesn't work because the return value only reaches up to `2147483647`, which is the highest a `long` variable can get. Using `unsigned long` should work, however this data type as it looks to me is not supported by the library.

Is there any other way to read timestamps?
Thanks for your help :)

**Comment by mobizt** [comment]
The library was updated to [v1.2.0](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/releases/tag/v1.2.0) which supports double and 64-bit signed/unsigned integer.

https://github.com/mobizt/Firebase-Arduino-WiFiNINA/blob/979cc49994940521bb06a070e260c741338bfc2b/examples/Basic/Basic.ino#L63-L70

**Comment by mobizt** [comment]
To get 64-bit number, you can use **getInt**.

**Comment by matzesoft** [comment]
Oups, yeah your right `unsigned long` is still to small.
But thanks for updating the library. Got it working now.
