### ISSUE TITLE
Nano RP2040 Connect support

### ISSUE THREAD

**Issue by tickietackie** [mobizt/Firebase-Arduino-WiFiNINA#29]
The Nano RP2040 Connect is built on the same platform, right?
Will it also be supported in the future, or is it already?

**Comment by mobizt** [comment]
It's different platform and not supported by the library and I have no plan on it.

**Comment by mobizt** [comment]
It's not supported by the [WiFi library](https://github.com/arduino-libraries/WiFiNINA#wifinina-library-for-arduino) (driver).

**Comment by tickietackie** [comment]
Sorry, I may ask again, because I do not really fully understand what is not supported.
I am using the WiFi NINA library with the RP2040 Connect. 
Is this not the library you mean or what do you refer to with "driver"?
The RP2040 has the Nina W102 chip.

https://docs.arduino.cc/hardware/nano-rp2040-connect

**Comment by mobizt** [comment]
It's not supported by library at this time and have no plan to make it.

**Comment by mobizt** [comment]
This is not the final decision until I tested everything and have the time to make it because I'm busy now.

**Comment by tickietackie** [comment]
Thanks for clarifying that.

**Comment by tickietackie** [comment]
We will use this library for firebase communication with an Arduino IoT firstly. 
But I can at least check if the same code would work with the RP2040 as well.
The Basic example is compiling fine for myself so far. If I have more information I will present it here.

**Comment by tickietackie** [comment]
So the Basic example works flawlessly on the RP2040. Will test the other stuff eventually and report back again.

**Comment by Raphael2908** [comment]
> So the Basic example works flawlessly on the RP2040. Will test the other stuff eventually and report back again.

Are you able to read and write data to a firebase real-time database?

**Comment by tickietackie** [comment]
Yes, that's what's in the examples, reading, writing and streaming data.

**Comment by Raphael2908** [comment]
Oh cool, how did you do it? I keep getting connection refused

**Comment by tickietackie** [comment]
https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/18 

Have a look at the issue above. Looks like you did not set up the input variables correctly for the library. It's not really intuitive if you never worked with RTDB, but just search through the closed issues of this repo and you will find all information eventually.

**Comment by Raphael2908** [comment]
Oh, I see. Thank you so much!
