### ISSUE TITLE
Stream does not receive data when it should

### ISSUE THREAD

**Issue by tickietackie** [mobizt/Firebase-Arduino-WiFiNINA#30]
I have a really weird problem. 
I have a stream listening on "/table_config/CUywk9RhoFTWTZTD4KuNcMvFDBC2/mcu_read/123456789".

I am updating the data below this path via a web app with the Firebase SDK.

When setting the path "table_config/CUywk9RhoFTWTZTD4KuNcMvFDBC2/mcu_read/123456789/configuration_per_state/In_Game" the stream gets the data as expected, but not when setting all data beneath "/table_config/CUywk9RhoFTWTZTD4KuNcMvFDBC2/mcu_read/123456789"

Listening with the web sdk for changes works fine in both occasions and the same stream path. There I get all updates when listening to the same path.

With this library it's not working as mentioned for both of them, but only the first. 
I also tested manual adaptations in the web console, which also works for on web and Arduino.

```
#include "Firebase_Arduino_WiFiNINA.h"

#define DATABASE_URL "xx" //<databaseName>.firebaseio.com or <databaseName>.<region>.firebasedatabase.app
#define DATABASE_SECRET "xx"

#define WIFI_SSID "xx"
#define WIFI_PASSWORD "xx"

//Define Firebase data object
FirebaseData fbdo;

FirebaseData stream;

unsigned long sendDataPrevMillis = 0;

String path = "/table_config/CUywk9RhoFTWTZTD4KuNcMvFDBC2/mcu_read/123456789";

int count = 0;

void setup()
{

  Serial.begin(115200);
  delay(100);
  Serial.println();

  Serial.print("Connecting to Wi-Fi");
  int status = WL_IDLE_STATUS;
  while (status != WL_CONNECTED)
  {
    status = WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    Serial.print(".");
    delay(100);
  }
  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();

  //Provide the autntication data
  Firebase.begin(DATABASE_URL, DATABASE_SECRET, WIFI_SSID, WIFI_PASSWORD);
  Firebase.reconnectWiFi(true);

  if (!Firebase.beginStream(stream, path))
  {
    Serial.println("Can't connect stream, " + stream.errorReason());
    Serial.println();
  }
}

void loop()
{

  if (!Firebase.readStream(stream))
  {
    Serial.println("Can't read stream, "+ stream.errorReason());
  }

  if (stream.streamTimeout())
  {
    Serial.println("Stream timed out, resuming...");
  }

  if (stream.streamAvailable())
  {
    count++;
    if (stream.dataType() == "null")
      count = 0;

    Serial.println("Stream data received... ");
    Serial.println("stream path: " + stream.streamPath());
    Serial.println("event path: " + stream.dataPath());
    Serial.println("data type: " + stream.dataType());
    Serial.println("event type: " + stream.eventType());
    Serial.print("value: ");
    if (stream.dataType() == "int")
      Serial.println(stream.intData());
    if (stream.dataType() == "int64")
      Serial.println(stream.int64Data());
    if (stream.dataType() == "uint64")
      Serial.println(stream.uint64Data());
    else if (stream.dataType() == "double")
      Serial.println(stream.doubleData());
    else if (stream.dataType() == "float")
      Serial.println(stream.floatData());
    else if (stream.dataType() == "boolean")
      Serial.println(stream.boolData() == 1 ? "true" : "false");
    else if (stream.dataType() == "string")
      Serial.println(stream.stringData());
    else if (stream.dataType() == "json")
      Serial.println(stream.jsonData());
    else if (stream.dataType() == "array")
      Serial.println(stream.arrayData());
    Serial.println();
  }
}
```

First call, which triggers an update on the arduino stream:
![image](https://user-images.githubusercontent.com/25544561/153938218-bc184ee9-15eb-4384-9322-bb2172f0f5b9.png)

and in web:

![Bildschirmfoto 2022-02-14 um 21 13 04](https://user-images.githubusercontent.com/25544561/153939343-d223588f-de79-487e-8c5b-3c78f1a79fe5.png)

Second update that only triggers an update in the web sdk, but not on the arduino
![image](https://user-images.githubusercontent.com/25544561/153938366-4efa10f0-c537-4727-9936-6ae7ec7bf20b.png)

Functions for updating the data in RTDB in typescript, which I also checked in the console that its working:
```
const sendInGameConfiguration = (
  stateConfiguration: ISendInGameConfigurationProps, tableId: number | string | null
): Promise<ISendApiRequestResponse> => {
  return new Promise((resolve, reject) => {
    const userId = auth.currentUser?.uid
    const idPath = tableId !== null ? tableId : "general";
    db.ref(`table_config/${userId}/mcu_read/${idPath}/configuration_per_state/${TableState.In_Game}`)
      .set(stateConfiguration).then((data) => {
        console.log('data ', data)
        resolve({
          error: false,
          code: 0,
        });
      }).catch((error) => {
        console.log('error ', error)
        reject({
          error: true,
          code: -1,
          message: error.message,
        });
      })
  })
}
```

and 

```
const sendConfig = (tableConfig: InitialTableState, tableId: string | number | null):
    Promise<ISendApiRequestResponse> => {
    return new Promise((resolve, reject) => {
        const userId = auth.currentUser?.uid
        const idPath = tableId !== null ? tableId : "general";
        const now = new Date();
        tableConfig.last_updated = Math.round(now.getTime() / 1000);

        db.ref(`/table_config/${userId}/mcu_read/${idPath}/`).
            set({ tableConfig }).then((data) => {
                console.log('data ', data)
                resolve({
                    error: false,
                    code: 0,
                });
            }).catch((error) => {
                console.log('error ', error)
                reject({
                    error: true,
                    code: -1,
                    message: error.message,
                });
            })
    })
}
```

The json data that gets updated looks like the following:

```
{
    "configuration_per_state": {
        "Idle": {
            "allowed_effects": [
                0,
                2,
                6,
                1,
                3,
                5,
                4
            ],
            "brightness": 10,
            "default_effect": {
                "type": 0
            }
        },
        "In_Game": {
            "allowed_effects": [
                2,
                6,
                1,
                3,
                5,
                4
            ],
            "brightness": 15,
            "duration": 1260,
            "field_master": {
                "default_effect": {
                    "type": 2
                }
            },
            "field_slave": {
                "default_effect": {
                    "type": 2
                }
            },
            "limit_game_duration": true,
            "remaining_duration": 1260,
            "state": 1
        }
    },
    "id": "123456789",
    "last_updated": 1644869223,
    "name": "test,
    "wifi_mode": 0
}
```

Does anyone know, what's going on here?

**Comment by mobizt** [comment]
The library works fine as it should.

You don't mention which device you used.

The problem can be out of memory when you work with large payload.

Use SAMD21 device with U-blox NINAbuilt-in.

**Comment by tickietackie** [comment]
I am using an Arduino Nano 33 IoT, which should not have a problem regarding memory for this purpose.
I am reading far bigger JSON data via http requests, or from sd cards.

**Comment by mobizt** [comment]
That's my assumption because you don't provide your device information and not need to compare something to prove something because of your previously provided info.

I confirmed that the stream works normally on my test which done before I replied.

You should understand the http stream behavior which only push the changes to the client.

If you store the same data to stream node, no changes and no data push to client.

**Comment by tickietackie** [comment]
Thanks for explain the http stream behaviour again. I am aware of this.
There are changes made in both examples I provided.
also in both ways its nearly the same amount of data that is changed.
But I will reduce the amount and test again. 
I will provide feedback then.

**Comment by mobizt** [comment]
The jason payload like you posted is ok.

**Comment by tickietackie** [comment]
Ok, I now at least know, when the data is received. 

Let's assume I am listening to "/table_config/".
Then when I am using the "set" method, so replacing all the content at this node, no data will be received with this library.
Otherwise, when I am using the "update" method on the root node, the new data will be received on the stream.

The interesting thing is, that when using the "set" or "update" method on a node below the root node, e.g. "/table_config/read/", the data will be received by the stream.

This does not look like expected behaviour to me.

**Comment by tickietackie** [comment]
And the 2. thing I noticed:
When you're updating 2 times really fast right after another, and it is the same data. Then the second update, will change nothing of course and the first update won't be received by the stream, which is also weird.
Because I can see the changes in the web console, but they are not propagated in this case to the Arduino.

**Comment by mobizt** [comment]
You need to understand the basic of stream features

All changes push to client by server in http stream, library is only listen to the push data.
Library can't send any request to server after stream connected.

If you overwrite the root, then the data under stream path which is the child of root will be changed then the data will push to client too.

**If you have any issue please contact Firebase team instead.**

Library is just directly Firebase REST API implementation, user needs to understand the concept of this Firebase REST service.

You can't compare this REST API to the features provided by Firebase and Admin SDKs because some are not available and are different API interfaces.

**Comment by mobizt** [comment]
> And the 2. thing I noticed: When you're updating 2 times really fast right after another, and it is the same data. Then the second update, will change nothing of course and the first update won't be received by the stream, which is also weird. Because I can see the changes in the web console, but they are not propagated in this case to the Arduino.

This is not true because I test with Android and Web client to iterate update the integer data 100,000 to 500,000 times without delay in iteration loop, the stream data received completely. No data missed.

**Comment by tickietackie** [comment]
1. This will also concern other people, that may want to use this library. Hence I really think posting these comments here is worth, as somebody else can find this directly and understand, what the limitations are of this library, as I think this is not really clearly described somewhere, or at least I couldn't find it. 
2. Of course can I compare different Firebase APIs. I mean the sense of the comparison is, to get an idea how they differ from each other. That's why I am asking these questions in the first place.

**Comment by mobizt** [comment]
Are you new to Firebase REST API?

**Comment by tickietackie** [comment]
> > And the 2. thing I noticed: When you're updating 2 times really fast right after another, and it is the same data. Then the second update, will change nothing of course and the first update won't be received by the stream, which is also weird. Because I can see the changes in the web console, but they are not propagated in this case to the Arduino.
> 
> This is not true because I test with Android and Web client to iterate update the integer data 100,000 to 500,000 times without delay in iteration loop, the stream data received completely. No data missed.

Ok, then I will investigate further, why this is happening on my side. Maybe this is just a coincidence. 
With these tests you do, there must be some issue on my side then.

**Comment by mobizt** [comment]
You should ask the Firebase team instead.

**Comment by tickietackie** [comment]
> Are you new to Firebase REST API?

Yes, as you can derive from my knowledge, I am.

**Comment by mobizt** [comment]
This is not the place to discuss the Firebase features.

This repo is for library issue related only.
