### ISSUE TITLE
ARDUINO PORTENTA H7

### ISSUE THREAD

**Issue by petkomatus** [mobizt/Firebase-Arduino-WiFiNINA#32]
Good day,

I want to ask if this library can be used for Arduino Portenta H7?

Thank you in advance.

**Comment by mobizt** [comment]
It is already stated in readme

> The library supports Arduino NANO 33 IoT, Arduino MKR WiFi 1010, Arduino MKR VIDOR 4000 and Arduino UNO WiFi Rev.2.

**Comment by mobizt** [comment]
You should use [such library](https://github.com/mobizt/Firebase-ESP8266) with external Client.

**Comment by petkomatus** [comment]
Good day,
can you please give an example?
