### ISSUE TITLE
Firebase_Arduino_WiFiNINA Memory Usage

### ISSUE THREAD

**Issue by JEG8** [mobizt/Firebase-Arduino-WiFiNINA#34]
Hello,

Thank you for your work on this library.

I am currently using the Firebase_Arduino_WiFiNINA library on an Arduino IOT 33 device. I am using both WiFi and Bluetooth capabilities (not at the same time) and am ensuring to disable whichever one I am not using. My code is somewhat large (49% of program space, 48% of dynamic memory). I am using the code below from Adafruit to observe free memory.

When I start my code, I have about 11000 reported as free memory between the heap and stack. The next two actions of "set int" and "update node" drop that number to 8000 and then down to 4000. I am worried I am approaching critically low memory. 

Is there any way to reduce the memory usage of this library? I noticed some notes in the github "read me" that mentioned optimization for each processor. Is memory usage a known drawback to this library? Any help/tips to reducing memory usage is greatly appreciated.

Regards,
Joe

// Adafruit Code - https://learn.adafruit.com/memories-of-an-arduino/measuring-free-memory

#ifdef __arm__
// should use uinstd.h to define sbrk but Due causes a conflict
extern "C" char* sbrk(int incr);
#else  // __ARM__
extern char *__brkval;
#endif  // __arm__

int freeMemory() {
  char top;
#ifdef __arm__
  return &top - reinterpret_cast<char*>(sbrk(0));
#elif defined(CORE_TEENSY) || (ARDUINO > 103 && ARDUINO != 151)
  return &top - __brkval;
#else  // __arm__
  return __brkval ? &top - __brkval : &top - __malloc_heap_start;
#endif  // __arm__
}

**Comment by mobizt** [comment]
It's normal in WiFi application.

**Comment by mobizt** [comment]
The library memory usage is optimized and short-lived dynamic allocated.
The persistent memory required when the socket connection opened.

**Comment by mobizt** [comment]
You should reduce your code memory usage instead of asking me to reduce the memory usage in the library.

**Comment by JEG8** [comment]
Thank you for the prompt response. I'll look into it. I didn't ask you to reduce the memory usage or change the library. I was asking if I could reduce memory usage in the method in which I write my application.

**Comment by mobizt** [comment]
I will update the library to allow user to clear internal memory usage that mostly used for payload.

**Comment by JEG8** [comment]
Thank you very much!

**Comment by JEG8** [comment]
Hi @mobizt ,

Thanks for adding in the fbdo.clear() function. 

I wanted to follow up on this issue to see if you had any advice for my application. I am using an Nano IOT33 with your Firebase and FirebaseJSON libraries. 

The program is reading data from sensors and sending it to Firebase. 

I am using your JSON formatter and passing the resultant string from:
json.toString(jsonVal, false); into the Firebase Update Node function ((Firebase.setJSON(fbdo, path, jsonVal))

When I start the program (after initializing/connecting Wifi, and initializing fbdo), I have about 4131 reported as free memory. After running the JSON Formatter, this drops to 3543.
Then After running the Firebase Push, this drops to 823...

After the Push, I am, running fbdo.clear() and json.clear() in an attempt to free up the memory from the payload. However, the free memory doesnt change. 

Is there something that I am missing with the implementation of your code?

Thank you for any help you can provide.

Joe

**Comment by mobizt** [comment]
You should post your code here instead of just saying what happen.

**Comment by mobizt** [comment]
Please try this simple code to print the free memory.
```cpp
#include <Arduino.h>

#ifdef __arm__
// should use uinstd.h to define sbrk but Due causes a conflict
extern "C" char *sbrk(int incr);
#else  // __ARM__
extern char *__brkval;
#endif // __arm__

int freeMemory()
{
    char top;
#ifdef __arm__
    return &top - reinterpret_cast<char *>(sbrk(0));
#elif defined(CORE_TEENSY) || (ARDUINO > 103 && ARDUINO != 151)
    return &top - __brkval;
#else  // __arm__
    return __brkval ? &top - __brkval : &top - __malloc_heap_start;
#endif // __arm__
}

int loop_counter = 0;

void setup()
{

    Serial.begin(115200);

#if defined(ARDUINO_ARCH_SAMD)
    while (!Serial)
        ;
#endif

    Serial.println();
}


void loop()
{

    Serial.println(freeMemory());

    String str;

    for (int i = 0; i < 500; i++)
        str += F("0123456789abcdef");

    Serial.println(freeMemory());
    delay(10000);
}

```

You will see that the funtion `freeMemory` does not report the correct value after dynamic memory deallocation.

**Comment by mobizt** [comment]
And the [source](https://learn.adafruit.com/memories-of-an-arduino/measuring-free-memory#sram-370031) you referred to also written that

> What freeMemory() is actually reporting is the space between the heap and the stack. it does not report any de-allocated memory that is buried in the heap. Buried heap space is not usable by the stack, and may be fragmented enough that it is not usable for many heap allocations either.

**Comment by JEG8** [comment]
Hi @mobizt ,

I appreciate you sending this over. I will try to put together a short form of the code to help.

So what is actually happening in the library when json.clear() is called? Is it de-allocating the memory? Is this usable memory or is it buried in the heap?

Is there a light weight alternative to using FirebaseJson? Should I form the Strings manually?

Thanks again.
Joe

**Comment by JEG8** [comment]
Hi @mobizt 

I removed my data (and replaced it with A,B,C, etc) to show you my method.

I use the same json object in other parts of my code to write to different sections of the DB. Each write function to a different database folder uses json.clear() at the top of the function to de-allocate the memory.

Free Memory Usage: See // POINTs defined in code below.

At Start of Program -> 6347
First Iteration.. // POINT A-> 6291
First Iteration.. // POINT B-> 6291
First Iteration.. // POINT C-> 6291
First Iteration.. // POINT D-> 5787
First Iteration.. // POINT E-> 4563
First Iteration.. // POINT F-> 2659

2nd Iteration.. // POINT A-> 2715
2nd Iteration.. // POINT B-> 2659
2nd Iteration.. // POINT C-> 2659
2nd Iteration.. // POINT D-> 2659
2nd Iteration.. // POINT E-> 2659
2nd Iteration.. // POINT F-> 1851

3rd Iteration.. // POINT A-> 1851
3rd Iteration.. // POINT B-> 1851
3rd Iteration.. // POINT C-> 1851
3rd Iteration.. // POINT D-> 1851
3rd Iteration.. // POINT E-> 1851
3rd Iteration.. // POINT F-> 1851

//----------------CODE------------------------------

//-----------------------------------------------------
void databaseWrite() {

// POINT A

    json.clear();

// POINT B

    String path = "/dev/SN/"; path += serNumStr; path += "/Status/";
    String str;
    
    json.setFloatDigits(2);

// POINT C

    json.set("A/", A);    
    json.set("B/", B);
    json.set("C/", C);
    json.set("D/", D);
    json.set("E/", E);
    json.set("F/", F);
    json.set("G/", G);
    json.set("H/", H);
    json.set("I/", I);
    json.set("J/", J);
    json.set("K/", K);
    json.set("L/", L);
    json.set("M/", M);
    json.set("N/", N);
    json.set("O/", O);
    json.set("P/", P);
    json.set("Q/", Q);
    json.set("R/", R);
    json.set("S/", S);
    json.set("T/", T);

// POINT D

    json.toString(str, false);

// POINT E

    updateFirebaseNode(path, str);

// POINT F
    
    return;
}

bool updateFirebaseNode(String path, String jsonStr){
   if (Firebase.updateNode(fbdo, path, jsonStr))
      {
      #ifdef FB_DEBUG 
        Serial.println("ok");
        Serial.println("path: " + fbdo.dataPath());
        Serial.println("type: " + fbdo.dataType());
        Serial.print("value: ");
        if (fbdo.dataType() == "json")
        Serial.println(fbdo.jsonData());
      #endif
       
      return true;
      }
    else
      {
        #ifdef FB_DEBUG 
          Serial.println("Firebase Update Node Unsuccessful");
          Serial.println("Error, " + fbdo.errorReason());
          Serial.println("Path: " + fbdo.dataPath());
        #endif
        
        return false;
      }
}
