### ISSUE TITLE
firebaseData.errorReason  - Error: not found, 404 Not Found

### ISSUE THREAD

**Issue by Karl-Gil** [mobizt/Firebase-Arduino-WiFiNINA#35]
Hi, I am trying to send data from my Arduino Uno WiFi Rev2 to firebase but it does not seem to work. Here is my code. I would like to send the number 1634631042000 to my real-time database. When I run the code, it connects to the internet but then when it tries to push data I get the error "Error: not found, 404 Not Found". Thank you

`/*
 * Created by K. Suwatchai (Mobizt)
 * 
 * Email: k_suwatchai@hotmail.com
 * 
 * Github: https://github.com/mobizt
 * 
 * Copyright (c) 2021 mobizt
 *
*/

//Example shows how to connect to Firebase RTDB and perform basic operation for set, get, push and update data to database

//Required WiFiNINA Library for Arduino from https://github.com/arduino-libraries/WiFiNINA

#include "Firebase_Arduino_WiFiNINA.h"

#define DATABASE_URL "humid-sample.firebaseio.com" //<databaseName>.firebaseio.com or <databaseName>.<region>.firebasedatabase.app
#define DATABASE_SECRET "__________________"
#define WIFI_SSID "_____________________"
#define WIFI_PASSWORD "__________"

//Define Firebase data object
FirebaseData fbdo;

void setup()
{

  Serial.begin(9600);
  delay(100);
  Serial.println();

  Serial.print("Connecting to Wi-Fi");
  int status = WL_IDLE_STATUS;
  while (status != WL_CONNECTED)
  {
    status = WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    Serial.print(".");
    delay(100);
  }
  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();

  //Provide the autntication data
  Firebase.begin(DATABASE_URL, DATABASE_SECRET, WIFI_SSID, WIFI_PASSWORD);
  Firebase.reconnectWiFi(true);

  String path = "/test";
  String jsonStr;

  Serial.print("Set int... ");

  unsigned long long val = 1634631042000;

  if (Firebase.setInt(fbdo, path + "/int/data", val)) //support large number
  {
    Serial.println("ok");
    Serial.println("path: " + fbdo.dataPath());
    Serial.println("type: " + fbdo.dataType());
    Serial.print("value: ");
    if (fbdo.dataType() == "int")
      Serial.println(fbdo.intData());
    if (fbdo.dataType() == "int64")
      Serial.println(fbdo.int64Data());
    if (fbdo.dataType() == "uint64")
      Serial.println(fbdo.uint64Data());
    else if (fbdo.dataType() == "double")
      Serial.println(fbdo.doubleData());
    else if (fbdo.dataType() == "float")
      Serial.println(fbdo.floatData());
    else if (fbdo.dataType() == "boolean")
      Serial.println(fbdo.boolData() == 1 ? "true" : "false");
    else if (fbdo.dataType() == "string")
      Serial.println(fbdo.stringData());
    else if (fbdo.dataType() == "json")
      Serial.println(fbdo.jsonData());
    else if (fbdo.dataType() == "array")
      Serial.println(fbdo.arrayData());
  }
  else
  {
    Serial.println("error, " + fbdo.errorReason());
  }

  Serial.println();

}

void loop()
{
}`

**Comment by mobizt** [comment]
The project URL in your code was not found.

You can click this like to check [https://humid-sample.firebaseio.com/](https://humid-sample.firebaseio.com/)

**Comment by mobizt** [comment]
The database URL should be taken from this

![database url](https://raw.githubusercontent.com/mobizt/Firebase-ESP8266/master/media/images/RTDB_URL.png)

**Comment by Karl-Gil** [comment]
Thank you for coming back to me, I made a new firebase and did as you instructed. Just to confirm, for the DATABASE_URL, do you use the full URL as you indicated in the image above, or do you just take your project id and then you insert .firebaseio.com. I tried both ways but am still getting an error. When using the full link I get an error connection refused and then when I try inserting my project id and then.firebaseio.com, I get the 404 error again.

**Comment by mobizt** [comment]
What is your new database url?

**Comment by mobizt** [comment]
When you create new project, you will get the full database url as
**https://<your_project_id>-default-rtdb.<your_region>.firebasedatabase.app/**

Then the database URL defined in your sketch will be
**<your_project_id>-default-rtdb.<your_region>.firebasedatabase.app**

**Comment by Karl-Gil** [comment]
I think I left the "HTTPS" in the URL, but I changed it an it is working now, thank you very much :)
