### ISSUE TITLE
.beginEnterprise

### ISSUE THREAD

**Issue by BensonSherman** [mobizt/Firebase-Arduino-WiFiNINA#39]
So I'd like to use this over an enterprise connection, and in the Wifinina library we'd use wifi.beginEnterprise to do that. I don't see such a method with this library but I do see a .begin method. Is there a way to use this library over an enterprise connection?

**Comment by mobizt** [comment]
This is the Firebase library.

The WiFi is on network stack, you should test it yourself.

**Comment by mobizt** [comment]
The SSID and PASSWORD parameters in `Firebase.begin` function are for WiFI reconnection.

To manage WiFi reconnection manually including the enterprise WIFI rconnection , you should do the following

1. Call  `Firebase.begin(DATABASE_URL, DATABASE_SECRET, "", "");`
2.  Call `Firebase.reconnectWiFi(false);`
3.  Check for WiFI disconnection and handle reconnection manually.

**Comment by rdl4199** [comment]
> 

![image](https://user-images.githubusercontent.com/69980967/165179643-39d371e6-eccd-4fc9-9ca3-afd388f53030.png)
Are any of these the database_secret?

**Comment by mobizt** [comment]
@[rdl4199](https://github.com/rdl4199) You should not post the off topic here.

You can ask in community forum or search google for Firebase database secret.

The database secret can be taken from **Project settings** > **Service accounts**.
