### ISSUE TITLE
I have an issue trying to send my Json Document with ".pushJSON" to firebase.

### ISSUE THREAD

**Issue by senenpalanca** [mobizt/Firebase-Arduino-WiFiNINA#4]
When I try to send a short document i can, but when I try to make more than 120 characters aprox. it fails to send to firebase. I mean, I can send the document but i don't receive any payload nor response, and the program stops.

**Comment by mobizt** [comment]
Maybe the memory problem. Please check the [free memory ](https://playground.arduino.cc/Code/AvailableMemory/)before calling the Firebase function.

The library will be rewritten to use less reserved memory in the next update (next month).

**Comment by senenpalanca** [comment]
Thank you very much for the quick response. I check that and I got "freeMemory()=1539", but I don't know how to interpret this result. maybe I have to divide my data and send it in two parts? Thank you again!!

**Comment by mobizt** [comment]
The update is available which provides more free memory and fixes the memory leak.
