### ISSUE TITLE
Automatoc node when using push method

### ISSUE THREAD

**Issue by bluenectar** [mobizt/Firebase-Arduino-WiFiNINA#42]
Dear mobizt,

I'm running on a project using nano and firebase, thankfully I found your helpful library.
But when I tried to push some value using push() method, seems Firebase generate an automatic ID using random character.
Can we eliminate that process so we can pass our json string as we want ?
Thanks and best regards,
Hery

**Comment by mobizt** [comment]
That related to the Firebase API that we can't change.

You can use set instead of push.

**Comment by bluenectar** [comment]
Dear mobizt,

I see, thanks for your prompt reply.
