### ISSUE TITLE
Arduino Nano Connect

### ISSUE THREAD

**Issue by Alex122192** [mobizt/Firebase-Arduino-WiFiNINA#43]
Hello!

I am working on Arduino NANo connect on Low power Solution.

I have a problem when I turn off the Wifi.

At first turn off the Wifi NINA with the command "WiFi.end();" and when I try to update the value on Firebase and turn on the WiFi again the Wifi Turns on well but I can't update any value after that My board starts to blinking LED on board.

Is Anny a solution?? or does exist any sequence specific to reconnecting to Firebase after Wifi connection is lost?

**Comment by mobizt** [comment]
There is nothing to do with library because your internet is gone.

You should check your internet connection.
