### ISSUE TITLE
error: connection refused

### ISSUE THREAD

**Issue by shaina-espulgar** [mobizt/Firebase-Arduino-WiFiNINA#47]
I've read [this one](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/18) and [this one](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/44). I've compiled with all your solutions but still, the same problem occurs.

My firmware is latest:

and here are my
![image](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/assets/72699933/bc574cb2-c7ed-4328-8d63-8fc005d731ec)

I've also renew the database secret.

My FIREBASE_HOST is in correct syntax.
![image](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/assets/72699933/c9c19734-917e-4c64-88c0-6515c00727f6)

My board is Arduino Nano 33 IOT

Sorry for the inconvenience. Badly need your help for this!

**Comment by mobizt** [comment]
The database URL (actually only host name) may not valid.
https://github.com/mobizt/Firebase-Arduino-WiFiNINA/blob/a74d6e49a662c677e8b8df12d5337c1ea4981612/examples/Basic/Basic.ino#L18

Please try to delete your database secret in your project and create new one.
Or create new project.

**Comment by mobizt** [comment]
I can confirm that this is not library issue.

If you have tried everything in your code and all credentials you provided are ok. You should check your internet connection included your WiFi AP, router and internet ISP.
