### ISSUE TITLE
Nano 33 iot connection lost and then refused

### ISSUE THREAD

**Issue by ShkhAsher** [mobizt/Firebase-Arduino-WiFiNINA#49]
Hi, I have implemented all the suggestions in previous issues but none of them work. I have updated the firmware with the correct Firebase SSL and secrets. I have also the correct Wi-Fi credentials. The hardware is also not an issue as the same code and PCB is working with MKR but not with nano 33 iot. The code works fine in submitting the data on the firebase cloud but stops working with the connection refused error first and then the connection lost error.
Can you suggest any other solution?

**Comment by mobizt** [comment]
Please read [this](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/18).

**Comment by mobizt** [comment]
You have to add your domain (database url) for certificate verification.

`Connection lost error` is because `no network connected` while `connection refused` is because `server connection (internet) problem`.

In both cases, you have to debug your code first.
