### ISSUE TITLE
WiFiNINA Watchdog Implementation with Firebase Read/Write

### ISSUE THREAD

**Issue by JEG8** [mobizt/Firebase-Arduino-WiFiNINA#51]
Hi - The WiFiNINA library includes a function void WiFiClass::setFeedWatchdogFunc(FeedHostProcessorWatchdogFuncPointer func), and the library seems to call void WiFiClass::feedWatchdog() periodically. 

Since your library is built upon WiFiNINA, will the watchdog function continue to be fed if I declare it before calling your functions? 

I want to make sure that if a poor WiFi signal causes a read/write function to take longer than the max watchdog reset time (16s), that it won't cause my chip to reset. 

Thanks!

**Comment by mobizt** [comment]
I don't think reset is the solution and it is not acceptable for most users.

Any way this library is outdated and developed many years ago to support MCU that relies on `WiFiNINA` library included Arduino UNO WiFi Rev.2 which has limited memory and program space.

If you don't use Arduino UNO WiFi Rev.2, you should use this new [FirebaseClient](https://github.com/mobizt/FirebaseClient) library instead.

**Comment by JEG8** [comment]
Hi Mobizt,

I know this library is no longer supported, but I was hoping you could help with an issue I am facing while I upgrade. 

Sometimes firebase tasks (get, push, update) take a long time to complete (> 2 min). I am using a 2 minute Watchdog timer to detect processor hangs, and being stuck in the firebase task causes the Watchdog to expire and restart my processor. This is very infrequent, and only happens about once over a few months.

Do you know what could be causing this? Could it be a bad connection to firebase? Expired token? Any ideas on how to fix this would be very much appreciated.

Thanks!
