### ISSUE TITLE
Firebase_Arduino_WiFiNINA_HTTPClient incorrectly named

### ISSUE THREAD

**Issue by Albazar** [mobizt/Firebase-Arduino-WiFiNINA#9]
Firebase_Arduino_WiFiNINA_HTTPClient (.h and .cpp) are both incorrectly named:
Firebase_Arduino_WiFiNINA_HTTPC**L**ient (.h / .cpp)

This makes Firebase_Arduino_WiFiNINA.h includes fail

See here:
https://stackoverflow.com/questions/58149775/error-using-firebase-arduino-wifinina-to-connect-to-firebase-from-arduino

**Comment by mobizt** [comment]
Thanks for informing the issue.

I have updated the library with the correct file name.
